services:
  recipe_suggester_ai_agent_web_server_nginx:
    build: ./web-server
    container_name: recipe_suggester_ai_agent_web_server_nginx
    volumes:
      - ./client/dist:/var/www/public
      - ./web-server/conf/default.development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - recipe_suggester_ai_agent_client_web
      - recipe_suggester_ai_agent_api_fastapi
    ports:
      - 8001:8001
      - 8002:8002
    networks:
      - network

  recipe_suggester_ai_agent_client_web:
    build: ./client
    container_name: recipe_suggester_ai_agent_client_web
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 8000
    depends_on:
      - recipe_suggester_ai_agent_api_fastapi
    volumes:
      - client_web_volume_node_modules:/app/node_modules
      - ./client:/app
    expose:
      - 8000
    networks:
      - network

  recipe_suggester_ai_agent_api_fastapi:
    build: ./server
    container_name: recipe_suggester_ai_agent_api_fastapi
    working_dir: /app
    command: poetry run fastapi dev main.py --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/app
    expose:
      - 8000
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  client_web_volume_node_modules:
