services:
  recipe_suggester_ai_agent_web_server_nginx:
    build: ./web-server
    restart: unless-stopped
    container_name: recipe_suggester_ai_agent_web_server_nginx
    volumes:
      - ./client/dist:/var/www/public
      - ./web-server/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - recipe_suggester_ai_agent_client_web
      - recipe_suggester_ai_agent_api_fastapi
    ports:
      - 8001:8001
      - 8002:8002
    networks:
      - network

  recipe_suggester_ai_agent_client_web:
    build: ./client
    restart: on-failure
    container_name: recipe_suggester_ai_agent_client_web
    working_dir: /app
    depends_on:
      - recipe_suggester_ai_agent_api_fastapi
    volumes:
      - ./client:/app
    networks:
      - network

  recipe_suggester_ai_agent_api_fastapi:
    build: ./server
    container_name: recipe_suggester_ai_agent_api_fastapi
    working_dir: /app
    volumes:
      - ./server:/app
    expose:
      - 8000
    networks:
      - network

networks:
  network:
    driver: bridge